
public class test {

	public static void main(String[] args) {

     System.out.println("例外が発生しました。");
	}

}
